### ISSUE TITLE
TBB include in switch module

### ISSUE THREAD

**Issue by Tyrrr** [noxrepo/nox#1] opened 2012-06-18 19:51 UTC
I called configure with --with-tbb=dir, which the configure script is ok with (it can link to the library). But when I compile nox, the switch module can't find the TBB includes.
I looked in the Makefile and the folowing variables are defined: TBB_INCLUDES, TBB_LDFLAGS TBB_LIBS.
But the compiler uses TBB_CPPFLAGS, which is not defined. By changing TBB_INCLUDES to TBB_CPPFLAGS I could circumvent the error.

**Comment by tootoonchian** [comment] 2012-06-18 19:56
You are right. Could you edit m4/ax_tbb.m4 file and replace TBB_INCLUDES with TBB_CPPFLAGS, and retry (need to run boot.sh and configure).

**Comment by Tyrrr** [comment] 2012-06-18 21:10
Yes, this fixed it.
But when I start nox_core with the switch module loaded, I get the following error: 00054|main|DBG:switch:
        Current state: ERROR
        Required state: INSTALLED
        Dependencies: 'openflow-manager' OK
        Error:
                Cannot open a dynamic library: 'file not found' or 'file not found'

Could this also be related to the tbb library or this another error?

**Comment by tootoonchian** [comment] 2012-06-18 21:36
Could you also edit src/coreapps/switch/Makefile.am, move TBB_LDFLAGS from switch_la_LIBADD to switch_la_LDFLAGS, and retry?

**Comment by Tyrrr** [comment] 2012-06-18 22:28
like this?

switch_la_LDFLAGS =                             \
    $(TBB_LDFLAGS)                              \
    $(AM_LDFLAGS) -export-dynamic -module       \
    -version-info $(SWITCH_LIB_VERSION)

switch_la_LIBADD =                              \
    $(TBB_LIBS)

It didn't work, but I didn't try with a fresh git clone. Will try again tomorrow. Do I have to run boot.sh again or is configure enough?

**Comment by tootoonchian** [comment] 2012-06-18 22:32
Yes, you'd need to run boot.sh again.
On Jun 18, 2012 6:28 PM, "Tyrrr" <
reply@reply.github.com>
wrote:

**Comment by Tyrrr** [comment] 2012-06-19 13:51
Nope, didn't work. If I move the tbb libs to /usr/local/lib, nox_core starts just fine, so it definitely can't find the libs with the non-standard installation.

**Comment by tootoonchian** [comment] 2012-06-19 17:09
Thanks! I will look into this asap.

**Comment by tootoonchian** [comment] 2012-06-22 20:05
I am inclined not to patch NOX to fix the latter issue (the former is a bug certainly):

The problem is that when the linker is loading the dynamic library (or program) file, it looks for the library's dependencies in the library search path. I can add the path for let's say TBB library to the library search path at build time (which will then be hardcoded in the binary), but it could as well be set at run time without any change to the code and further hassles.

So, there are two workarounds to this problem:

a) install the library in a directory in the library search path
b) before running NOX, add the library's directory to the runtime library search path using the LD_LIBRARY_PATH environment variable, e.g.: "LD_LIBRARY_PATH=~/libs/:$LD_LIBRARY_PATH ./nox_core ..."

If you find workarounds satisfactory, I can close this issue and later add a note about it in the FAQ page.

**Comment by Tyrrr** [comment] 2012-06-27 21:57
I don't quite understand why you wouldn't want to hardcode the path to the TBB library, when I explicitly told configure the location by adding --with-tbb=, but these workarounds are also fine by me.

**Closed as completed** 2012-08-17 15:46 UTC
Labels: bug
